version: 2

sources:
  - name: lakehouse
    schema: main
    description: "Camada Silver do Data Lakehouse"
    tables:
      - name: order_items
        description: "Itens de pedidos processados na camada Silver"
        # Configuração para o adaptador dbt-duckdb saber ler o arquivo parquet
        meta:
          external_location: "{{ var('lakehouse_path') }}/silver/order_items/*.parquet"